#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Install a VibeBridge Node environment and write configs/node.toml.

Required:
  --repo PATH
  --mode ws|http
  --register-token TOKEN

Mode-specific:
  --main-server-url URL      Required for --mode ws
  --main-register-url URL    Required for --mode http

Optional:
  --venv PATH                Default: <repo>/.venv-vibebridge-node
  --config PATH              Default: <repo>/configs/node.toml
  --host HOST                Default: 127.0.0.1
  --port PORT                Default: 4456
  --db-path PATH             Default: database/node.db
  --node-id ID               Default: empty
  --node-name NAME           Default: empty
  --labels CSV               Default: empty
  --capabilities CSV         Default: claude,codex
  --advertise-host HOST      Default: empty
  --advertise-port PORT      Default: 0
  --force-config             Overwrite an existing config file

Example:
  bash skills/vibebridge-node-install/scripts/install_node.sh \
    --repo /root/VibeBridge \
    --mode ws \
    --main-server-url ws://main.example.com:8000/ws/node \
    --register-token abc123
EOF
}

trim() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "$value"
}

toml_array_from_csv() {
  local raw="${1:-}"
  local first=1
  local item
  printf '['
  IFS=',' read -r -a parts <<< "$raw"
  for item in "${parts[@]}"; do
    item="$(trim "$item")"
    [ -z "$item" ] && continue
    if [ "$first" -eq 0 ]; then
      printf ', '
    fi
    printf '"%s"' "$item"
    first=0
  done
  printf ']'
}

REPO_DIR=""
VENV_DIR=""
CONFIG_PATH=""
MODE=""
MAIN_SERVER_URL=""
MAIN_REGISTER_URL=""
REGISTER_TOKEN=""
HOST="127.0.0.1"
PORT="4456"
DB_PATH="database/node.db"
NODE_ID=""
NODE_NAME=""
LABELS=""
CAPABILITIES="claude,codex"
ADVERTISE_HOST=""
ADVERTISE_PORT="0"
FORCE_CONFIG="0"

while [ $# -gt 0 ]; do
  case "$1" in
    --repo)
      REPO_DIR="$2"
      shift 2
      ;;
    --venv)
      VENV_DIR="$2"
      shift 2
      ;;
    --config)
      CONFIG_PATH="$2"
      shift 2
      ;;
    --mode)
      MODE="$2"
      shift 2
      ;;
    --main-server-url)
      MAIN_SERVER_URL="$2"
      shift 2
      ;;
    --main-register-url)
      MAIN_REGISTER_URL="$2"
      shift 2
      ;;
    --register-token)
      REGISTER_TOKEN="$2"
      shift 2
      ;;
    --host)
      HOST="$2"
      shift 2
      ;;
    --port)
      PORT="$2"
      shift 2
      ;;
    --db-path)
      DB_PATH="$2"
      shift 2
      ;;
    --node-id)
      NODE_ID="$2"
      shift 2
      ;;
    --node-name)
      NODE_NAME="$2"
      shift 2
      ;;
    --labels)
      LABELS="$2"
      shift 2
      ;;
    --capabilities)
      CAPABILITIES="$2"
      shift 2
      ;;
    --advertise-host)
      ADVERTISE_HOST="$2"
      shift 2
      ;;
    --advertise-port)
      ADVERTISE_PORT="$2"
      shift 2
      ;;
    --force-config)
      FORCE_CONFIG="1"
      shift 1
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [ -z "$REPO_DIR" ] || [ -z "$MODE" ] || [ -z "$REGISTER_TOKEN" ]; then
  usage >&2
  exit 1
fi

REPO_DIR="$(cd "$REPO_DIR" && pwd)"
VENV_DIR="${VENV_DIR:-$REPO_DIR/.venv-vibebridge-node}"
CONFIG_PATH="${CONFIG_PATH:-$REPO_DIR/configs/node.toml}"

if [ ! -f "$REPO_DIR/requirements.txt" ] || [ ! -f "$REPO_DIR/app.py" ]; then
  echo "Repo path does not look like VibeBridge: $REPO_DIR" >&2
  exit 1
fi

case "$MODE" in
  ws)
    if [ -z "$MAIN_SERVER_URL" ]; then
      echo "--main-server-url is required for --mode ws" >&2
      exit 1
    fi
    MAIN_REGISTER_URL=""
    ;;
  http)
    if [ -z "$MAIN_REGISTER_URL" ]; then
      echo "--main-register-url is required for --mode http" >&2
      exit 1
    fi
    MAIN_SERVER_URL=""
    if [ -z "$ADVERTISE_HOST" ] && { [ "$HOST" = "0.0.0.0" ] || [ "$HOST" = "::" ]; }; then
      echo "Warning: HTTP registration mode with host=$HOST usually needs --advertise-host" >&2
    fi
    ;;
  *)
    echo "--mode must be ws or http" >&2
    exit 1
    ;;
esac

mkdir -p "$(dirname "$CONFIG_PATH")" "$REPO_DIR/logs"

python3 -m venv "$VENV_DIR"
"$VENV_DIR/bin/pip" install --upgrade pip
"$VENV_DIR/bin/pip" install -r "$REPO_DIR/requirements.txt"

if [ -f "$CONFIG_PATH" ] && [ "$FORCE_CONFIG" != "1" ]; then
  echo "Config already exists, leaving it unchanged: $CONFIG_PATH"
else
  if [ -x /bin/zsh ]; then
    DEFAULT_SHELL="/bin/zsh"
  else
    DEFAULT_SHELL="/bin/bash"
  fi

  cat > "$CONFIG_PATH" <<EOF
# Generated by skills/vibebridge-node-install/scripts/install_node.sh

[server]
host = "$HOST"
port = $PORT

[database]
path = "$DB_PATH"

[node]
id = "$NODE_ID"
name = "$NODE_NAME"
register_token = "$REGISTER_TOKEN"
labels = $(toml_array_from_csv "$LABELS")
capabilities = $(toml_array_from_csv "$CAPABILITIES")
main_server_url = "$MAIN_SERVER_URL"
main_register_url = "$MAIN_REGISTER_URL"
advertise_host = "$ADVERTISE_HOST"
advertise_port = $ADVERTISE_PORT

[auth]
platform_mode = false
jwt_secret = ""

[filesystem]
file_tree_max_nodes = 2500
file_tree_max_depth = 6

[terminal]
default_shell = "$DEFAULT_SHELL"

[providers.claude]
tool_approval_timeout_ms = 55000
context_window = 160000

[providers.codex]
tool_approval_timeout_ms = 55000
query_idle_timeout_ms = 0
EOF
fi

cat <<EOF
Node environment ready.

Repo:   $REPO_DIR
Venv:   $VENV_DIR
Config: $CONFIG_PATH
Mode:   $MODE

Suggested start command:
  cd $REPO_DIR
  nohup env PATH=/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin \\
    $VENV_DIR/bin/python -m uvicorn app:app --host $HOST --port $PORT \\
    >> $REPO_DIR/logs/node.log 2>&1 < /dev/null &

Suggested validation:
  curl -sf http://127.0.0.1:$PORT/health
EOF
