#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Install a VibeBridge Main environment and write configs/main.toml.

Required:
  --repo PATH

Optional:
  --venv PATH                  Default: <repo>/.venv-vibebridge-main
  --config PATH                Default: <repo>/configs/main.toml
  --host HOST                  Default: 0.0.0.0
  --port PORT                  Default: 4457
  --db-path PATH               Default: database/auth.db
  --jwt-secret SECRET          Default: omitted so Main auto-generates one
  --node-addresses CSV         Optional advanced compatibility setting
  --node-register-tokens CSV   Optional advanced compatibility setting
  --build-frontend             Run npm install && npm run build in frontend-src
  --force-config               Overwrite an existing config file

Example:
  bash skills/vibebridge-main-install/scripts/install_main.sh \
    --repo /root/VibeBridge \
    --host 0.0.0.0 \
    --port 8000 \
    --db-path database/auth.db
EOF
}

trim() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "$value"
}

toml_array_from_csv() {
  local raw="${1:-}"
  local first=1
  local item
  printf '['
  IFS=',' read -r -a parts <<< "$raw"
  for item in "${parts[@]}"; do
    item="$(trim "$item")"
    [ -z "$item" ] && continue
    if [ "$first" -eq 0 ]; then
      printf ', '
    fi
    printf '"%s"' "$item"
    first=0
  done
  printf ']'
}

REPO_DIR=""
VENV_DIR=""
CONFIG_PATH=""
HOST="0.0.0.0"
PORT="4457"
DB_PATH="database/auth.db"
JWT_SECRET=""
NODE_ADDRESSES=""
NODE_REGISTER_TOKENS=""
BUILD_FRONTEND="0"
FORCE_CONFIG="0"

while [ $# -gt 0 ]; do
  case "$1" in
    --repo)
      REPO_DIR="$2"
      shift 2
      ;;
    --venv)
      VENV_DIR="$2"
      shift 2
      ;;
    --config)
      CONFIG_PATH="$2"
      shift 2
      ;;
    --host)
      HOST="$2"
      shift 2
      ;;
    --port)
      PORT="$2"
      shift 2
      ;;
    --db-path)
      DB_PATH="$2"
      shift 2
      ;;
    --jwt-secret)
      JWT_SECRET="$2"
      shift 2
      ;;
    --node-addresses)
      NODE_ADDRESSES="$2"
      shift 2
      ;;
    --node-register-tokens)
      NODE_REGISTER_TOKENS="$2"
      shift 2
      ;;
    --build-frontend)
      BUILD_FRONTEND="1"
      shift 1
      ;;
    --force-config)
      FORCE_CONFIG="1"
      shift 1
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [ -z "$REPO_DIR" ]; then
  usage >&2
  exit 1
fi

REPO_DIR="$(cd "$REPO_DIR" && pwd)"
VENV_DIR="${VENV_DIR:-$REPO_DIR/.venv-vibebridge-main}"
CONFIG_PATH="${CONFIG_PATH:-$REPO_DIR/configs/main.toml}"

if [ ! -f "$REPO_DIR/requirements.txt" ] || [ ! -f "$REPO_DIR/main_server.py" ]; then
  echo "Repo path does not look like VibeBridge: $REPO_DIR" >&2
  exit 1
fi

mkdir -p "$(dirname "$CONFIG_PATH")" "$REPO_DIR/logs"

python3 -m venv "$VENV_DIR"
"$VENV_DIR/bin/pip" install --upgrade pip
"$VENV_DIR/bin/pip" install -r "$REPO_DIR/requirements.txt"

if [ "$BUILD_FRONTEND" = "1" ]; then
  if ! command -v npm >/dev/null 2>&1; then
    echo "npm is required for --build-frontend" >&2
    exit 1
  fi
  (
    cd "$REPO_DIR/frontend-src"
    npm install
    npm run build
  )
  rm -rf "$REPO_DIR/dist"
  cp -R "$REPO_DIR/frontend-src/dist" "$REPO_DIR/dist"
fi

if [ -f "$CONFIG_PATH" ] && [ "$FORCE_CONFIG" != "1" ]; then
  echo "Config already exists, leaving it unchanged: $CONFIG_PATH"
else
  {
    cat <<EOF
# Generated by skills/vibebridge-main-install/scripts/install_main.sh

[server]
host = "$HOST"
port = $PORT

[database]
path = "$DB_PATH"
EOF

    if [ -n "$JWT_SECRET" ]; then
      cat <<EOF

[auth]
jwt_secret = "$JWT_SECRET"
EOF
    fi

    if [ -n "$NODE_ADDRESSES" ] || [ -n "$NODE_REGISTER_TOKENS" ]; then
      cat <<EOF

[main]
node_addresses = $(toml_array_from_csv "$NODE_ADDRESSES")
node_register_tokens = $(toml_array_from_csv "$NODE_REGISTER_TOKENS")
EOF
    fi
  } > "$CONFIG_PATH"
fi

cat <<EOF
Main environment ready.

Repo:   $REPO_DIR
Venv:   $VENV_DIR
Config: $CONFIG_PATH

Suggested start command:
  cd $REPO_DIR
  nohup env PATH=/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin \\
    $VENV_DIR/bin/python -m uvicorn main_server:app --host $HOST --port $PORT \\
    >> $REPO_DIR/logs/main.log 2>&1 < /dev/null &

Suggested validation:
  curl -sf http://127.0.0.1:$PORT/health
EOF
